source 'http://rubygems.org'

gem 'rails', '3.0.5'
gem 'sqlite3'
gem 'devise'
gem 'rails_admin', :git => 'git://github.com/sferik/rails_admin.git'
gem 'will_paginate', '3.0.pre2'
gem 'admin_data', '1.1.11'
gem 'ice_cube'
gem 'pg'
gem 'delayed_job'
gem 'heroku_backup_task'
gem 'gravatar_image_tag'
gem 'heroku_san'
gem 'faker'

group :test, :development do
  gem 'rspec-rails'
  gem 'annotate-models'
  gem 'rspec'
  gem 'spork', '0.9.0.rc4'
  gem 'webrat'
  gem 'factory_girl_rails'
  gem 'fakeweb'
end
