login: &login
  encoding: unicode
  adapter: postgresql
  username: actionpods
  password: actionpods

production:
  <<: *login
  database: actionpods_production

development:
  <<: *login
  database: actionpods_development

test:
  <<: *login
  database: actionpods_test
